# Generated by Django 5.0.1 on 2026-01-01 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_plan_seo_description_plan_seo_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='Unique order identifier', max_length=32, unique=True)),
                ('buyer_email', models.EmailField(help_text="Buyer's email address for delivery", max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('buyer_name', models.CharField(blank=True, help_text="Optional: Buyer's name", max_length=200)),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Amount paid (captures price at purchase time)', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('payment_provider', models.CharField(choices=[('payoneer', 'Payoneer'), ('lemon_squeezy', 'Lemon Squeezy'), ('manual', 'Manual Payment')], default='manual', help_text='Payment gateway used', max_length=50)),
                ('payment_provider_id', models.CharField(blank=True, help_text='Transaction ID from payment provider', max_length=255)),
                ('access_token', models.CharField(db_index=True, editable=False, help_text='Secure token for downloading purchased plan', max_length=64, unique=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times file has been downloaded')),
                ('max_downloads', models.PositiveIntegerField(default=5, help_text='Maximum allowed downloads (prevents sharing)')),
                ('access_expires_at', models.DateTimeField(blank=True, help_text='Optional: Access expiration date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this order')),
                ('plan', models.ForeignKey(help_text='The plan being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer_email', '-created_at'], name='orders_orde_buyer_e_3f261e_idx'), models.Index(fields=['payment_status', '-created_at'], name='orders_orde_payment_8bdf8b_idx')],
            },
        ),
    ]
