# Generated by Django 5.0.1 on 2026-01-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Admin notes about payment verification'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('payoneer', 'Payoneer Transfer'), ('bank_transfer', 'Bank Transfer (SWIFT)')], help_text='Payment method used (Payoneer or Bank Transfer)', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Payment receipt uploaded by customer', null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When payment was verified by admin', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('processing', 'Processing'), ('completed', 'Approved'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
    ]
