# Generated by Django 5.2.10 on 2026-01-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_admin_comment_order_payment_method_and_more'),
        ('plans', '0021_plan_pack_3_price_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(help_text='The plan being purchased (deletion blocked if orders exist)', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='plans.plan'),
        ),
    ]
