# Generated by Django 6.0 on 2026-01-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Old URL path (e.g., /old-page/)', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='New URL path or full URL', max_length=255)),
                ('redirect_type', models.CharField(choices=[('301', 'Permanent (301)'), ('302', 'Temporary (302)')], default='301', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 chars max for Google). Leave empty to use default.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (160 chars max). Leave empty to use default.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (optional, less important for modern SEO)', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if different from default')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=100)),
                ('og_description', models.CharField(blank=True, help_text='Description for social media', max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='Social media preview image', null=True, upload_to='seo/og_images/')),
                ('index', models.BooleanField(default=True, help_text='Allow search engines to index this page')),
                ('follow', models.BooleanField(default=True, help_text='Allow search engines to follow links')),
                ('schema_type', models.CharField(blank=True, help_text='Schema.org type (e.g., Product, Article)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_seometa_content_a438cb_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
