# Generated by Django 5.0.1 on 2026-01-02 16:23

import apps.branding.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_type', models.CharField(choices=[('main_logo', 'Main Logo (Header)'), ('footer_logo', 'Footer Logo'), ('favicon', 'Favicon')], help_text='Type of logo (only one per type)', max_length=20, unique=True)),
                ('image', models.ImageField(help_text='Upload logo (SVG, PNG, WEBP, JPG)', upload_to=apps.branding.models.logo_upload_path, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'webp', 'jpg', 'jpeg'])])),
                ('alt_text', models.CharField(default='Site Logo', help_text='Alternative text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Set as active logo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_logos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
                'ordering': ['logo_type'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title overlay', max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Optional short description', max_length=500)),
                ('image', models.ImageField(help_text='Upload slider image (JPG, PNG, WEBP)', upload_to='presentation/slider/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('link_url', models.URLField(blank=True, help_text='Optional link when image is clicked')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Display this slide on the website')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presentation Slide',
                'verbose_name_plural': 'Presentation Slider',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
