# Generated by Django 6.0 on 2026-01-01 14:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name of the plan', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('reference', models.CharField(help_text='Internal reference code (e.g., PL-2024-001)', max_length=50, unique=True)),
                ('plan_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use'), ('other', 'Other')], default='residential', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(help_text='Number of bedrooms', validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.DecimalField(decimal_places=1, help_text='Number of bathrooms (e.g., 2.5 for 2 full + 1 half)', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_area_sqm', models.DecimalField(decimal_places=2, help_text='Total floor area in square meters', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Area (m²)')),
                ('total_area_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated from m²', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Area (ft²)')),
                ('description', models.TextField(help_text='Public description visible to customers')),
                ('engineer_notes', models.TextField(blank=True, help_text='Internal notes for engineers/admin only (not visible to customers)')),
                ('free_plan_file', models.FileField(blank=True, help_text='Preview plan without dimensions (PDF)', null=True, upload_to='plans/free/%Y/%m/')),
                ('paid_plan_file', models.FileField(blank=True, help_text='Full plan with dimensions (PDF)', null=True, upload_to='plans/paid/%Y/%m/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD for the full plan', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_published', models.BooleanField(default=False, help_text='Make this plan visible on the website')),
                ('featured', models.BooleanField(default=False, help_text='Show this plan in featured sections')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('downloads_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='plans.category')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload plan images (PNG, JPG)', upload_to='plans/images/%Y/%m/')),
                ('image_type', models.CharField(choices=[('floor_plan', 'Floor Plan'), ('elevation', 'Elevation'), ('section', 'Section'), ('3d_render', '3D Render'), ('photo', 'Photo'), ('other', 'Other')], default='floor_plan', max_length=20)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_primary', models.BooleanField(default=False, help_text='Use as the main thumbnail image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Plan Image',
                'verbose_name_plural': 'Plan Images',
                'ordering': ['display_order', '-is_primary', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['slug'], name='plans_plan_slug_65d1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_published', '-created_at'], name='plans_plan_is_publ_09ff77_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['category', 'is_published'], name='plans_plan_categor_5b493b_idx'),
        ),
    ]
