# Generated by Django 6.0 on 2026-01-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Custom SEO description (160 chars max). Leave empty to auto-generate.', max_length=160),
        ),
        migrations.AddField(
            model_name='plan',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom SEO title (60 chars max). Leave empty to auto-generate.', max_length=60),
        ),
    ]
