# Generated by Django 6.0 on 2026-01-02 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_seo_description_plan_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='architect_design_notes',
            field=models.TextField(blank=True, help_text='Architect’s design notes shown publicly (design logic, functional choices, build simplicity)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='budget_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], help_text='Budget level (optional)', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='climate_suitability',
            field=models.CharField(blank=True, help_text='Climate suitability (optional)', max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of floors/levels (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='plan',
            name='plot_type',
            field=models.CharField(blank=True, help_text='Plot type (flat, sloped, narrow, corner, etc.) (optional)', max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='roof_type',
            field=models.CharField(blank=True, help_text='Roof type (e.g., gable, hip, flat) (optional)', max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='suggested_plot_size',
            field=models.CharField(blank=True, help_text='Suggested plot size (e.g., 12m x 20m) (optional)', max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='target_user',
            field=models.CharField(blank=True, help_text='Target user (first-time builder, rental, guest house, etc.) (optional)', max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='wall_system',
            field=models.CharField(blank=True, help_text='Wall system (e.g., masonry, timber frame) (optional)', max_length=120),
        ),
    ]
