# Generated by Django 5.0.1 on 2026-01-02 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_architect_design_notes_plan_budget_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('files_updated', 'Files Updated'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('soft_deleted', 'Soft Deleted'), ('restored', 'Restored'), ('hard_deleted', 'Hard Deleted')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan Audit Log',
                'verbose_name_plural': 'Plan Audit Logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan Slug History',
                'verbose_name_plural': 'Plan Slug History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='plans_plan_is_publ_09ff77_idx',
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='plans_plan_categor_5b493b_idx',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_published',
        ),
        migrations.AddField(
            model_name='plan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the plan was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who soft-deleted this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag (keeps orders intact)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='language_content',
            field=models.JSONField(blank=True, default=dict, help_text='Localized content keyed by language code (e.g., EN/FR)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='Last admin who modified this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='publish_status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('published', 'Published')], db_index=True, default='unpublished', help_text='Controls whether the plan is publicly visible', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last publish action', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='unpublished_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last unpublish action', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='unpublished_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last unpublished this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_unpublished', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='unpublished_reason',
            field=models.CharField(blank=True, help_text='Optional note explaining why the plan was unpublished', max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='free_plan_file',
            field=models.FileField(blank=True, help_text='Preview plan without dimensions (PDF only)', null=True, upload_to='plans/free/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='paid_plan_file',
            field=models.FileField(blank=True, help_text='Full plan with dimensions (PDF only)', null=True, upload_to='plans/paid/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['publish_status', '-created_at'], name='plans_plan_publish_366ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['category', 'publish_status'], name='plans_plan_categor_0d31bf_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_deleted', 'publish_status'], name='plans_plan_is_dele_bdf497_idx'),
        ),
        migrations.AddField(
            model_name='planauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planauditlog',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='planslughistory',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='plans.plan'),
        ),
    ]
