# Generated by Django 5.0.1 on 2026-01-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_planauditlog_planslughistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='enable_gumroad_payment',
            field=models.BooleanField(default=True, help_text='Enable or disable Gumroad payment for this plan. Payment button will only show if both this is enabled AND Gumroad URL is provided.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='gumroad_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the paid version of this plan (e.g., https://gumroad.com/l/your-product)', max_length=500),
        ),
    ]
