# Generated by Django 6.0 on 2026-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_add_draft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='gumroad_revit_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the Revit (.RVT) file. Payments remain on Gumroad.', max_length=500),
        ),
        migrations.AddField(
            model_name='plan',
            name='revit_available',
            field=models.BooleanField(default=False, help_text='Toggle on when an editable Revit (RVT) file is available for this plan.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='revit_notes',
            field=models.TextField(blank=True, help_text='Optional context describing what is included in the Revit file.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='revit_version',
            field=models.CharField(blank=True, help_text='Revit version compatibility (e.g., Revit 2022).', max_length=50),
        ),
        migrations.AlterField(
            model_name='planauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('files_updated', 'Files Updated'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('drafted', 'Marked Draft'), ('soft_deleted', 'Soft Deleted'), ('restored', 'Restored'), ('hard_deleted', 'Hard Deleted')], max_length=50),
        ),
    ]
