# Generated by GitHub Copilot on 2026-01-05
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_plan_paid_pdf_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_reference', models.CharField(max_length=50)),
                ('plan_title', models.CharField(max_length=200)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file_errors', models.JSONField(blank=True, default=list)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Deletion Log',
                'verbose_name_plural': 'Plan Deletion Logs',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
