# Generated by Django 5.0.1 on 2026-01-05 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_plandeletionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='free_3d_caption',
            field=models.CharField(blank=True, help_text='Optional caption shown next to the free 3D preview', max_length=200),
        ),
        migrations.AddField(
            model_name='plan',
            name='free_3d_image',
            field=models.ImageField(blank=True, help_text='Optional free 3D preview image without dimensions', null=True, upload_to='plans/free_3d/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated plan reference (e.g., FHP-2026-0007)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='total_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically synced with the m² value', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Area (ft²)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='total_area_sqm',
            field=models.DecimalField(decimal_places=2, help_text='Total floor area in square meters (enter either m² or ft²)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Area (m²)'),
        ),
    ]
