# Generated by Django 5.0.1 on 2026-01-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_plan_free_3d_caption_plan_free_3d_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ifc_imperial_available',
            field=models.BooleanField(default=False, help_text='Offer the IFC export using imperial conventions.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='ifc_imperial_gumroad_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the imperial IFC export.', max_length=500),
        ),
        migrations.AddField(
            model_name='plan',
            name='ifc_metric_available',
            field=models.BooleanField(default=False, help_text='Offer the IFC export using metric conventions.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='ifc_metric_gumroad_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the metric IFC export.', max_length=500),
        ),
        migrations.AddField(
            model_name='plan',
            name='revit_imperial_available',
            field=models.BooleanField(default=False, help_text='Offer the editable Revit file in imperial (ft) formatting.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='revit_imperial_gumroad_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the imperial Revit export.', max_length=500),
        ),
        migrations.AddField(
            model_name='plan',
            name='revit_metric_available',
            field=models.BooleanField(default=False, help_text='Offer the editable Revit file in metric (m) formatting.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='revit_metric_gumroad_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the metric Revit export.', max_length=500),
        ),
        migrations.AddField(
            model_name='planreferencesequence',
            name='paid_pdf_imperial_available',
            field=models.BooleanField(default=False, help_text='Offer an imperial (ft²) version of the paid PDF via Gumroad.'),
        ),
        migrations.AddField(
            model_name='planreferencesequence',
            name='paid_pdf_imperial_gumroad_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the imperial PDF (ft, ft²).', max_length=500),
        ),
        migrations.AddField(
            model_name='planreferencesequence',
            name='paid_pdf_metric_available',
            field=models.BooleanField(default=True, help_text='Offer a metric (m²) version of the paid PDF via Gumroad.'),
        ),
        migrations.AddField(
            model_name='planreferencesequence',
            name='paid_pdf_metric_gumroad_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the metric PDF (m, m²).', max_length=500),
        ),
    ]
