# Generated by Django 5.0.1 on 2026-01-05 23:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_plan_ifc_imperial_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_pro_pack', models.BooleanField(default=False, help_text='Show the Pack 3 – Pro BIM grouping on plan pages and in admin.')),
                ('pro_pack_label', models.CharField(blank=True, help_text="Optional heading override for Pack 3 (defaults to 'Pack 3 · Pro BIM Deliverables').", max_length=120)),
                ('pro_pack_summary', models.CharField(blank=True, help_text='Short descriptor shown near Pack 3 cards on the frontend.', max_length=255)),
                ('pro_pack_notes', models.TextField(blank=True, help_text='Long-form notes for Pack 3 (supports Markdown-safe plain text).')),
                ('dwg_file', models.FileField(blank=True, help_text='Optional DWG or DXF deliverable stored locally. Leave empty if not offered.', null=True, upload_to='plans/pro/dwg/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['dwg', 'dxf', 'zip'])])),
                ('dwg_file_label', models.CharField(blank=True, help_text="Optional call-to-action label for the DWG button (defaults to 'Download DWG').", max_length=120)),
                ('dwg_file_description', models.CharField(blank=True, help_text='Optional caption displayed beneath the DWG download button.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pack_configuration', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Plan Pack Configuration',
                'verbose_name_plural': 'Plan Pack Configurations',
            },
        ),
    ]
