# Generated by Django 5.0.1 on 2026-01-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_planpackconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='paid_pdf_imperial_available',
            field=models.BooleanField(default=False, help_text='Offer the paid PDF in imperial (ft, ft²) formatting with its own Gumroad product.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='paid_pdf_imperial_gumroad_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the imperial paid PDF variant.', max_length=500),
        ),
        migrations.AddField(
            model_name='plan',
            name='paid_pdf_metric_available',
            field=models.BooleanField(default=True, help_text='Offer the paid PDF in metric (m, m²) formatting with a dedicated Gumroad link.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='paid_pdf_metric_gumroad_url',
            field=models.URLField(blank=True, help_text='Gumroad checkout link for the metric paid PDF variant.', max_length=500),
        ),
    ]
