# Generated by Django 6.0 on 2026-01-06 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_plan_paid_pdf_imperial_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ifc_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD for the IFC deliverable. Applies to both metric and imperial files.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plan',
            name='revit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD for the editable Revit deliverable. Applies to both metric and imperial files.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='planpackconfiguration',
            name='dwg_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD for the DWG/DXF deliverable (applies to all unit formats).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD for the dimensioned PDF (Pack 2 · Standard). Applies to both metric and imperial variants.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
