# Generated by Django 6.0 on 2026-01-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_plan_ifc_price_plan_revit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pack2_zip_gumroad_reference',
            field=models.CharField(blank=True, help_text='Gumroad product ID or reference for the Pack 2 ZIP. Expected structure: /metric/ and /imperial/ folders inside PACK2-Standard-{reference}.zip. Hosted on Gumroad.', max_length=200, verbose_name='Pack 2 ZIP Reference'),
        ),
        migrations.AddField(
            model_name='plan',
            name='pack3_zip_gumroad_reference',
            field=models.CharField(blank=True, help_text='Gumroad product ID or reference for the Pack 3 Pro BIM ZIP. Expected structure: /metric/ and /imperial/ folders inside PACK3-Pro-{reference}.zip. Hosted on Gumroad.', max_length=200, verbose_name='Pack 3 ZIP Reference'),
        ),
    ]
