# Generated by Django 6.0 on 2026-01-06 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_add_zip_delivery_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pack_2_zip_file',
            field=models.FileField(blank=True, help_text='Upload ONE ZIP named PACK2-Standard-<reference>.zip that contains /metric/pdf/ and /imperial/pdf/ directories.', null=True, upload_to='plans/packs/pack2/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
        migrations.AddField(
            model_name='plan',
            name='pack_3_zip_file',
            field=models.FileField(blank=True, help_text='Upload ONE ZIP named PACK3-Pro-<reference>.zip that contains /metric/ and /imperial/ subfolders for Revit, IFC, and DWG assets.', null=True, upload_to='plans/packs/pack3/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
