# Generated by Django 6.0 on 2026-01-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0018_plan_pack_2_zip_file_plan_pack_3_zip_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pack2_zip_gumroad_reference',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='pack3_zip_gumroad_reference',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='pack_2_zip_file',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='pack_3_zip_file',
        ),
        migrations.AddField(
            model_name='plan',
            name='pack_2_gumroad_zip_url',
            field=models.URLField(blank=True, help_text='Single Gumroad ZIP delivering Pack 2 (contains both Metric and Imperial PDFs).', max_length=500, verbose_name='Pack 2 Gumroad ZIP URL'),
        ),
        migrations.AddField(
            model_name='plan',
            name='pack_3_gumroad_zip_url',
            field=models.URLField(blank=True, help_text='Single Gumroad ZIP delivering Pack 3 (Metric + Imperial Revit/IFC/DWG).', max_length=500, verbose_name='Pack 3 Gumroad ZIP URL'),
        ),
    ]
