# Generated by Django 6.0 on 2026-01-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0019_remove_plan_pack2_zip_gumroad_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='ifc_imperial_available',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='ifc_imperial_gumroad_url',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='ifc_metric_available',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='ifc_metric_gumroad_url',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='paid_pdf_imperial_available',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='paid_pdf_imperial_gumroad_url',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='paid_pdf_metric_available',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='paid_pdf_metric_gumroad_url',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='revit_imperial_available',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='revit_imperial_gumroad_url',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='revit_metric_available',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='revit_metric_gumroad_url',
        ),
        migrations.RemoveField(
            model_name='planreferencesequence',
            name='paid_pdf_imperial_available',
        ),
        migrations.RemoveField(
            model_name='planreferencesequence',
            name='paid_pdf_imperial_gumroad_url',
        ),
        migrations.RemoveField(
            model_name='planreferencesequence',
            name='paid_pdf_metric_available',
        ),
        migrations.RemoveField(
            model_name='planreferencesequence',
            name='paid_pdf_metric_gumroad_url',
        ),
    ]
