# Generated by Django 6.0 on 2026-01-07 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0020_remove_plan_ifc_imperial_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pack_3_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pack 3 selling price in USD. Pack 3 stays hidden on the website until a positive price is set here.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD for the dimensioned PDF (Pack 2 · Standard).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
