# Generated by Django 5.0.1 on 2026-01-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('contact_admin', 'Contact - Admin Notification'), ('order_admin', 'Order - Admin Notification'), ('order_confirmation', 'Order - Buyer Confirmation'), ('order_approved', 'Order - Payment Approved'), ('order_rejected', 'Order - Payment Rejected'), ('download_link', 'Order - Download Link'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('related_contact_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='notificatio_status_d84ea4_idx'), models.Index(fields=['category', '-created_at'], name='notificatio_categor_e61cfa_idx')],
            },
        ),
    ]
