# Generated by Django 5.0.1 on 2026-01-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=500)),
                ('country_code', models.CharField(db_index=True, default='UN', max_length=2)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], db_index=True, default='desktop', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['country_code', 'created_at'], name='analytics_v_country_769da3_idx'), models.Index(fields=['url', 'created_at'], name='analytics_v_url_9cc0cc_idx')],
            },
        ),
    ]
