# Generated by Django 5.0.1 on 2026-01-01 16:48

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('plans', 'Question About Plans'), ('purchase', 'Purchase Support'), ('technical', 'Technical Question'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment (PDF, JPG, PNG, ZIP - Max 10MB)', null=True, upload_to=apps.core.models.contact_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
